local testing = require('testing')('vfs')
local vfs = require('vfs')
local fs = require('fs')
local assert = require('assert')
local buffer = require('buffer')

testing("we shall be standing in srcdir for the other tests to work", function()
   assert(fs.is_dir('testdata'))
   assert(fs.is_reg('vfs_test.lua'))
end)

testing("Root", function()
   local root = vfs.Root()
   assert(not root:exists('arborescence.jpg'))
   root:mount('testdata')
   assert(root:exists('arborescence.jpg'))
   assert.equals(root:readfile('arborescence.jpg'), fs.readfile('testdata/arborescence.jpg'))
   root:mount('.', 'src')
   assert.equals(root:readfile('arborescence.jpg'), fs.readfile('testdata/arborescence.jpg'))
   assert.equals(root:readfile('src/vfs_test.lua'), fs.readfile('./vfs_test.lua'))

   -- vfs readfile returns a buffer
   assert(buffer.is_buffer(root:readfile('arborescence.jpg')))
end)

testing("default Root instance", function()
   -- calls on vfs itself are proxied to a default Root instance
   vfs.mount('testdata', 'assets')
   assert(not vfs.exists('arborescence.jpg'))
   assert(not vfs.exists('testdata/arborescence.jpg'))
   assert(vfs.exists('assets/arborescence.jpg'))
   assert.equals(vfs.readfile('assets/arborescence.jpg'), fs.readfile('testdata/arborescence.jpg'))
end)

testing("mounting subdirectories into subdirectories", function()
   local root = vfs.Root()
   root:mount('testdata', 'x/y')
   root:mount('testdata/sub', 'x/z')
   assert(root:exists('x/y/arborescence.jpg'))
   assert(root:exists('x/z/HighHopes.txt'))
end)
